<h1 style="text-align: center;">Pagina de Editar</h1>
<hr>


<form action="#" method="POST" style="text-align: center;">
    <input type="hidden" name="idalunos"  value="<?php echo $_POST["idalunos"] ?? $dados["idalunos"] ?> ">
    <label></label>
    <input type="text" name="nome" class="btn btn-outline-dark" placeholder="Nome" value="<?php echo $_POST["nome"] ?? $dados["nome"] ?>">
    <label></label>
    <input type="text" name="matricula"  class="btn btn-outline-dark" placeholder="Matricula" value="<?php echo $_POST["matricula"] ?? $dados["matricula"] ?>">
    <label></label>
    <input type="text" name="cidade" class="btn btn-outline-dark" placeholder="Cidade" value="<?php echo $_POST["cidade"] ?? $dados["cidade"] ?>">
    <button type="submit" class="btn btn-outline-success" value="editar">Salvar Edição</button>
</form>