<h1 style="text-align: center;">Pagina de listar</h1>

<hr>

<table class="container table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Matricula</th>
            <th>Cidade</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
    <?php
        foreach ($dados as $linha) {
            $idalunos = $linha['idalunos'];

            echo "<tr>
                <td>{$linha['idalunos']}</td>
                <td>{$linha['nome']}</td>
                <td>{$linha['matricula']}</td>
                <td>{$linha['cidade']}</td>
                <td>
                    <a href='/editar?idalunos={$idalunos}' class='btn btn-outline-warning'>Editar</a>
                    <button type='button' onclick='excluirid({$idalunos})' data-bs-toggle='modal' data-bs-target='#exampleModal' class='btn btn-outline-danger'>Excluir</button>
                </td>
            </tr>
            ";
        }
        ?>
    </tbody>
</table>
<!-- Modal -->
<div class='modal fade' id='exampleModal' tabindex='-1' aria-labelledby='exampleModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h1 class='modal-title fs-5' id='exampleModalLabel'>Excluir Aluno</h1>
                <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
            </div>
            <div class='modal-body'>
                Deseja Excluir Esse Aluno ?
                <input type="hidden" id="idatual">
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cancelar</button>
                <button type='button' onclick='confirmar()' class='btn btn-danger'>Confirmar</button> 
            </div>
        </div>
    </div>
</div>

<script>
    function excluirid(id) {
        document.getElementById("idatual").value = id;
    }
    function confirmar() {
        let idalunos = document.getElementById("idatual").value;
        location.href = '/excluir?idalunos=' + idalunos;
    }
    // function confirmar(id) {
    //     if (true === confirm('Tem certeza?')) {
    //         location.href = '/excluir?id='+id;
    //     }
    // }
</script>
<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js'
    integrity='sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3'
    crossorigin='anonymous'></script>