<h1>Pagina de listar</h1>

<hr>

<table class="container table table-striped table-houver">
    <thead class="table-dark">
        <tr>
            <td>ID</td>
            <td>Nome</td>
            <td>Matricula</td>
            <td>Cidade</td>
            <td>Acão</td>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($alunos as $linha) {
            $id = $linha['id'];

            echo "<tr>
                    <td>{$linha['id']}</td>
                    <td>{$linha['nome']}</td>
                    <td>{$linha['matricula']}</td>
                    <td>{$linha['cidade']}</td>
                <td>
                    <a href='/editar?id={$id}' class='btn btn-outline-warning'>Editar</a>
                    <a href='/excluir?id={$id}' class='btn btn-outline-danger'>Excluir</a>
                </td>
            </tr>";
        }
        ?>
    </tbody>
</table>