<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">


<h1>Pagina menu</h1>
<nav class="container">
    <a class="btn btn-outline-dark" href="/">inicio</a>
    <a class="btn btn-outline-dark" href="/listar">Listar</a>
    <a class="btn btn-outline-dark" href="/novo">Novo</a>
</nav>