<h1>Cadastrar Novo Aluno</h1>
<hr>
<card class="">
    <form action="#" method='POST'>
        <label></label>
        <input type="text" name="nome" placeholder="Nome">
        <label></label>
        <input type="text" name="matricula" placeholder="Matricula">
        <label></label>
        <input type="text" name="cidade" placeholder="Cidade">
        <input type="submit" value="criar">
    </form>
</card>